### ISSUE TITLE
Pi-hole Widget CORS

### ISSUE THREAD

**Issue by chrisg991** [benphelps/homepage#17]
I have added the Pi-hole widget to each of my Pi-hole entries on Homepage and both are saying "PiHole API Error". The message below is given in Chrome's console.

`homepage.lan/:1 Access to fetch at 'http://192.168.3.4:8181/admin/api.php' from origin 'http://homepage.lan' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by benphelps** [comment]
I've added the option to proxy the API requests,

```yaml
widget:
  type: pihole
  url: http://pi.hole
  proxy: true # this will enable the CORS proxy
```

**Comment by id-ic** [comment]
I'm getting follow error. 
`
The Same Origin Policy disallows reading the remote resource at http://10.10.10.10/admin/api.php. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.`

**Comment by chrisg991** [comment]
> I've added the option to proxy the API requests,
> 
> ```yaml
> widget:
>   type: pihole
>   url: http://pi.hole
>   proxy: true # this will enable the CORS proxy
> ```

Thanks for looking at this so quickly. I've pulled the latest version and am not getting an internal server error when I try and load the page. (This is with or without the `proxy:true` line).

The container logs are giving the following information:
```
TypeError: handler is not a function
    at Server.<anonymous> (/app/server.js:19:11)
    at Server.emit (node:events:513:28)
    at parserOnIncoming (node:_http_server:980:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
```

**Comment by benphelps** [comment]
It was an unrelated bug, which has been fixed now.

**Comment by chrisg991** [comment]
> It was an unrelated bug, which has been fixed now.

Thanks!

**Comment by jbeck22** [comment]
I'm still getting the API error.  I have tried to target the IP and port directly (http://192.168.1.254/admin) and I have tried with the proxy setting set to true and still nothing.

**Comment by benphelps** [comment]
What version of PiHole are you running?

**Comment by jbeck22** [comment]
> What version of PiHole are you running?

v5.18.1

**Comment by jbeck22** [comment]
I'm getting a similar error with the SAB API call:


`TypeError [ERR_INVALID_URL]: Invalid URL
at new NodeError (node:internal/errors:393:5)
at URL.onParseError (node:internal/url:564:9)
at new URL (node:internal/url:644:5)
at genericProxyHandler (/app/.next/server/pages/api/services/proxy.js:379:19)
at async Object.apiResolver (/app/node_modules/.pnpm/next@12.3.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/api-utils/node.js:366:9)
at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js:469:9)
at async Object.fn (/app/node_modules/.pnpm/next@12.3.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js:719:37)
at async Router.execute (/app/node_modules/.pnpm/next@12.3.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/router.js:247:36)
at async NextNodeServer.run (/app/node_modules/.pnpm/next@12.3.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/base-server.js:346:29)
at async NextNodeServer.handleRequest (/app/node_modules/.pnpm/next@12.3.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/base-server.js:284:20) {
input: 'undefined/api/?apikey=d164c44b2bbffd08c7f731990e25fc2d&output=json&mode=queue',
code: 'ERR_INVALID_URL'
}`
