### ISSUE TITLE
[Bug] Service discovery

### ISSUE THREAD

**Issue by Cinj216** [benphelps/homepage#343]
**Describe the bug**
Service discovery grabs any label that has the word "homepage" and creates an erroneous blank entry for that container.

**Expected behavior**
For this to not happen.

**Screenshots**
Container grabbed by Service Discovery displayed at top of page:
![Screenshot_20221006_132437](https://user-images.githubusercontent.com/113621758/194390273-57b24325-665b-4ca1-b8e6-60bfe2d34a10.png)

Container I actually set up further down the page (to demonstrate it's the same container):
![Screenshot_20221006_132451](https://user-images.githubusercontent.com/113621758/194390555-32e89c03-ae5d-4e40-8c7c-f8b5021e217c.png)

Labels the container applies to itself creating the problem:
![Screenshot_20221006_132515](https://user-images.githubusercontent.com/113621758/194390702-d84cbe7e-2588-4c28-9e73-751d58f092a5.png)

**Configuration**
Likely irrelevant.

**Additional context**
I have no control over the container labelling itself with it's homepage url so there's nothing I can do on my end to fix this. Homepage should ignore improperly formatted labels such as this or use a different labelling scheme that won't be likely to cause such a conflict. For whatever reason, this only started occurring today; previous versions didn't exhibit this behavior.

**Comment by benphelps** [comment]
Oh that's very interesting, thank you for the report.

We'll try to get this fixed by the next release.

**Comment by Cinj216** [comment]
> Oh that's very interesting, thank you for the report.
> 
> We'll try to get this fixed by the next release.

I edited with one additional detail right as you replied, not sure if you caught it so I'll paraphrase it here. It only started occurring with the latest version, if that helps narrow down where the problem is. Thanks for your time.

**Comment by benphelps** [comment]
This should be fixed now, if not, feel free to reopen.

**Comment by Cinj216** [comment]
Strangely, the info widget misalignment I complained of previously is seemingly fixed but the service discovery issue remains unfortunately.
