### ISSUE TITLE
If disk name is invalid, should display "NaN" instead of using the default path "/"

### ISSUE THREAD

**Issue by jackblk** [benphelps/homepage#56]
Just my opinion but this is kinda misleading. If the user doesn't check the console log (especially in Docker compose), they they will never know that the path is invalid.

**Comment by benphelps** [comment]
This has more to do with the `node-os-utils` package, since it's the one doing the fallback to `/`.  I should be able to verify the path exists first on my side however and show a more informative error.

**Comment by benphelps** [comment]
I've fixed this in the latest commit :)

**Comment by medoix** [comment]
I am running the nightly container and am still seeing this error in the container logs
```info: disk name invalid, using / as default```
